export const homePage = String.raw`
<section class="hero"><div class="wrap hero-grid">
<div><div class="eyebrow">Built for South African reality</div><h1>Safety should start before the emergency.</h1><p class="lead">WITH. is being designed as a personal safety network that connects the things people already use. Phones, watches, trusted people, transport, nearby businesses and professional responders can become one protection loop.</p><div class="actions"><a class="btn" href="/with-safety-network/join">Join early</a><a class="btn alt" href="/with-safety-network/how-it-works">See how it works</a><button class="btn alt" data-open-ai>Ask WITH.</button></div><p class="micro"><b>We are early.</b> This is a research prototype. No responder partnerships or protection guarantees are being claimed.</p></div>
<figure class="hero-photo"><img src="https://images.unsplash.com/photo-1683110534724-42b900154a34?auto=format&fit=crop&w=1600&q=82" alt="Two South African women walking together in Johannesburg"><figcaption class="photo-copy"><strong>Ordinary life should not require constant fear.</strong><br>WITH. is meant to fit into the life people already live.</figcaption></figure>
</div></section>
<section style="padding:0"><div class="wrap kicker-row"><div><b>Before</b><span>Prepare the safety chain.</span></div><div><b>During</b><span>Keep the protected moment connected.</span></div><div><b>If something changes</b><span>Verify and act through more than one path.</span></div><div><b>After</b><span>Connect recovery and support.</span></div></div></section>
<section><div class="wrap section-head"><div><div class="eyebrow">The value</div><h2>Not another panic button.</h2></div><div class="section-copy"><p>Most safety products start after someone knows they are in danger and can still reach a button. WITH. starts earlier.</p><p><b>The goal is continuity.</b> One lost phone, one ignored notification or one unavailable responder should not end the whole safety chain.</p></div></div><div class="wrap cards"><article class="card"><h3>Guardian</h3><p>Protect a journey, ride, walk or short vulnerable moment with a defined session and expected outcome.</p><a href="/with-safety-network/how-it-works"><b>Explore Guardian →</b></a></article><article class="card"><h3>Private Risk</h3><p>Prepare check ins, trusted people, a safe destination and an escalation plan when the concern may involve someone known.</p><a href="/with-safety-network/how-it-works"><b>Explore Private Risk →</b></a></article><article class="card"><h3>Assistance Points</h3><p>Turn real businesses and institutions into verified places where someone can reach practical help.</p><a href="/with-safety-network/assistance-points"><b>See the model →</b></a></article></div></section>
<section class="dark"><div class="wrap section-head"><div><div class="eyebrow" style="color:var(--safe)">The protection loop</div><h2>One failure should not end the chain.</h2></div><p class="section-copy">The system is designed around handoffs. If one layer disappears, the next layer should already know enough to continue.</p></div><div class="wrap loop"><div class="step active"><span>01</span><b>Prepare</b><p>Readiness, people, devices and plan.</p></div><div class="step"><span>02</span><b>Guard</b><p>Protect the journey or moment.</p></div><div class="step"><span>03</span><b>Notice and verify</b><p>SOS or a broken expected pattern.</p></div><div class="step"><span>04</span><b>Act and recover</b><p>Escalate, reach help and support recovery.</p></div></div><div class="wrap" style="margin-top:28px"><a class="btn safe" href="/with-safety-network/how-it-works">See the full loop</a></div></section>
<section><div class="wrap people-strip"><figure class="photo-card"><img src="https://images.unsplash.com/photo-1683534239440-3b741f48a7ea?auto=format&fit=crop&w=1200&q=82" alt="South African woman working at a table in Johannesburg"><figcaption class="photo-copy"><strong>People before product.</strong><br>Safety should work at home, at work, on campus and on the move.</figcaption></figure><div class="panel"><div class="eyebrow">The mission</div><h2>Connect what already exists.</h2><p class="section-copy">South Africa already has emergency services, private security, GBV support, smartphones, watches, businesses, campuses, families and communities.</p><p class="section-copy"><b>The opportunity is to connect those systems earlier and more intelligently.</b></p><a class="btn alt" href="/with-safety-network/mission">Read the mission</a></div></div></section>
<section><div class="wrap trust-pair"><div class="never"><div class="eyebrow">What we will not do</div><h3>Safety cannot become surveillance.</h3><p>No public map of nearby women. No secret partner tracking. No sale of individual movement histories. No claim that AI can predict an assault.</p></div><div class="always"><div class="eyebrow">What we are trying to build</div><h3>A calm system that becomes useful when something changes.</h3><p>User controlled sharing. Minimal data. Clear handoffs. Real help. Transparent boundaries.</p></div></div><div class="wrap" style="margin-top:22px"><a class="btn alt" href="/with-safety-network/trust">Read the Trust Centre</a></div></section>
<section><div class="wrap cta"><div class="split"><div><div class="eyebrow">Join the network</div><h2>Help shape WITH. before launch.</h2><p>We are looking for potential users, businesses, employers, campuses, banks, insurers, property groups, response providers and community organisations.</p></div><div><a class="btn" href="/with-safety-network/join">Choose how you want to participate</a></div></div></div></section>
`;